---
version: "2.1"
services:
  traefik:
    image: "traefik:v2.8"
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.email=me@chandl.io"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - "CF_API_EMAIL=me@chandl.io"
      - "CF_DNS_API_TOKEN=<redacted>"
    volumes:
      - "/opt/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
  nextcloud:
    # copied and pasted config/nginx/site-confs/default from https://pastebin.com/2tgLjVpw
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`storage.lan.chandl.io`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=myresolver"
      - "traefik.http.services.nextcloud.loadBalancer.server.port=80"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /opt/nextcloud-config:/config
      - /mnt/hdd/nextcloud:/data
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`media.lan.chandl.io`) && PathPrefix(`/prowlarr`)"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.tls.certresolver=myresolver"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/hdd/config/prowlarr:/config
    restart: unless-stopped
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.media.rule=Host(`media.lan.chandl.io`)"
      - "traefik.http.routers.media.entrypoints=websecure"
      - "traefik.http.routers.media.tls.certresolver=myresolver"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/hdd/config/jellyfin:/config
      - /mnt/hdd/library/tv:/data/tvshows
      - /mnt/hdd/library/movies:/data/movies
      - /dev/vchiq:/dev/vchiq
    restart: unless-stopped
  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`media.lan.chandl.io`) && PathPrefix(`/sonarr`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls.certresolver=myresolver"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/hdd/config/sonarr:/config
      - /mnt/hdd/library/tv:/tv #optional
      - /mnt/hdd/downloads/transmission:/downloads #optional
    restart: unless-stopped
  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`media.lan.chandl.io`) && PathPrefix(`/radarr`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls.certresolver=myresolver"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/hdd/config/radarr:/config
      - /mnt/hdd/library/movies:/movies #optional
      - /mnt/hdd/downloads/transmission:/downloads #optional
    restart: unless-stopped
  transmission:
    image: ghcr.io/linuxserver/transmission:latest
    container_name: transmission
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`media.lan.chandl.io`) && PathPrefix(`/transmission`)"
      - "traefik.http.routers.transmission.entrypoints=websecure"
      - "traefik.http.routers.transmission.tls.certresolver=myresolver"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/hdd/config/transmission:/config
      - /mnt/hdd/downloads/transmission:/downloads
    restart: unless-stopped
