apiVersion: v1
kind: Service
metadata:
  name: timetrack-db
  labels:
    app: timetrack-db
spec:
  ports:
    - port: 3306
  selector:
    app: timetrack-db
    tier: db
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-volume
  labels:
    app: timetrack-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timetrack-db
  labels:
    app: timetrack-db
spec:
  selector:
    matchLabels:
      app: timetrack-db
  replicas: 1
  template:
    metadata:
      labels:
        app: timetrack-db
    spec:
      serviceAccountName: default
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      initContainers:
      containers:
        - name: timetrack-db
          image: ghcr.io/linuxserver/mariadb
          imagePullPolicy: "IfNotPresent"
          env:
            - name: TZ
              value: "Etc/UTC"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-password
                  key: password
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: timetrack-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-timetrack-password
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: timetrack-config
                  key: MYSQL_DATABASE
          ports:
            - name: timetrack-db
              containerPort: 3306
          volumeMounts:
            - name: mariadb-volume
              mountPath: /config
      volumes:
        - name: mariadb-volume
          persistentVolumeClaim:
            claimName: mariadb-volume