---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: timetrack-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  tls:
  - hosts:
    - timetrack.lan.chandl.io
    secretName: timetrack-certs
  rules:
  - host: timetrack.lan.chandl.io
    http:
      paths:
      - path: /
        backend:
          serviceName: timetrack-service
          servicePort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: timetrack-service
  labels:
    run: timetrack-service
spec:
  selector:
    app: timetrack-service
  ports:
    - protocol: TCP
      port: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timetrack-service
  labels:
    app: timetrack-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timetrack-service
  template:
    metadata:
      labels:
        app: timetrack-service
    spec:
      containers:
        - name: timetrack
          image: 'registry.lan.chandl.io/timetrack:latest'
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: reports
              mountPath: /usr/src/timetrack/reports
          env:
            - name: HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: timetrack-config
                  key: HOSTNAME
            - name: TYPEORM_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: timetrack-config
                  key: TYPEORM_USERNAME
            - name: TYPEORM_PORT
              valueFrom:
                configMapKeyRef:
                  name: timetrack-config
                  key: TYPEORM_PORT
            - name: TYPEORM_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: timetrack-config
                  key: TYPEORM_DATABASE
            - name: TYPEORM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-timetrack-password
                  key: password
      restartPolicy: Always
      volumes:
        - name: reports
          emptyDir: {}
